version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: newman run Desktop/Tests.postman_collection.json --environment Desktop/prod.postman_environment.json
